### PR TITLE
7 image models page UI

### PR DESCRIPTION
**Pull request by 10Yaly**
This branch has add the models images and also the relative model
page for front-end.

### CODE REVIEW

**Comment by thogb** [comment]
Wrong branch, should be fornt_end.

**Comment by 10Yaly** [comment]
> Wrong branch, should be fornt_end.
Should I revert this merge issue?

**Comment by thogb** [comment]
Yea lets do that and new one to merge front_end.

**Comment by 10Yaly** [comment]
> Yea lets do that and new one to merge front_end.

Thanks!

**Pull request merged**
