### PR TITLE
Text to image API

### PR DESCRIPTION
**Pull request by gusprauwa**
I have added additional third party API for text-to-image API for backup resources. The first API is now getting really slow. I adjust the API endpoint with the functional spesification documents: https://docs.google.com/document/d/1yMv6Ku2RxctlIyRDWTS6gjDIu8FhOGqs8AKZHOD6rrY/edit

### CODE REVIEW

**Review by thogb — APPROVED** [review]

**Comment by thogb** [comment]
> First of all, thank you, Bagus, for the hard work in researching the AI API integration. Your effort is greatly appreciated, and it's an important step forward.
> 
> That being said, I noticed that the current code only sets up a route, which allows the frontend to potentially retrieve an image URL. However, there's no defined solution for storing the images yet. We need to think about how we can design a model for this and look into how MongoDB can be used to store the images efficiently.
> 
> Once again, great job on the progress so far, and let's continue refining this aspect!

We are using S3 to store images, audio, video and all media. I have already added the credentials for that. The two routes here can be used for testing. I will use this two route as reference and rush out the all the endpoints for the image prompts as this is must have. Then can continue frontend, video and should have features.

**Review by thogb — CHANGES_REQUESTED** [review]
There is merge conflict.
This one should be merged before you open next PR (which uses branch created from this PR's branch).
Can you check with the conventions for lcov? Should the testing tool's reporting output be included in our repository or to be ignored (place in .gitignore to ignore the coverage folder). I think only the testing code should be included, any outputs should be ignored (reduce repository size by ignoring generated code not directly used by the app).

**Comment by gusprauwa** [comment]
do you know how to proceed to this change request?

**Comment by thogb** [comment]
> do you know how to proceed to this change request? @thogb
> 
> I think it should be included in gitignore based on google search:
> 
> "Ignore the Coverage Outputs: The generated reports (e.g., the coverage folder produced by tools like LCOV) should be added to your .gitignore file. This practice helps keep your repository size manageable by not tracking files that are generated during the build or test process."

Do these:

Ignore coverage:
checkout to this branch locally. In the /backend/.gitignore add new line "coverage" to ignore this folder.
git checkout text-to-image-api
git add .
git commit -m "your message"

Install prettier and husky:
Open the root folder in terminal
npm i

Solve conflict:
git checkout dev
git pull
git checkout text-to-image-api
git merge dev

With vs code IDE solve the conflict.

**Comment by thogb** [comment]
Merged in wrong order. 
this is the older one should have been merged. 
Coverage report was not gitignored.

**Comment by Jesssieeee** [comment]
> @TomatoesBurner @gusprauwa Merged in wrong order. this is the older one should have been merged first. Coverage report was not gitignored.

I have sloved it

**Comment by TomatoesBurner** [comment]
> @TomatoesBurner @gusprauwa Merged in wrong order. this is the older one should have been merged first. Coverage report was not gitignored.
I've resolved the conflict using GitHub Editor. @gusprauwa I recommend that next time before initiating a merge, first merge the code from the dev branch with the branch you're submitting, resolve conflicts locally, and then push to GitHub. Be especially careful with VSCode, as it might push files with unresolved conflicts to GitHub.
image

**Pull request merged**
