### PR TITLE
Front end

### PR DESCRIPTION
**Pull request by thogb**
Merge front end to dev.
We should no longer use the front_end and back_end. Just use dev.
Need to have both in the same branch, so can run both locally.

### CODE REVIEW

**Review by 10Yaly — APPROVED** [review]
Good job!

**Comment by cloud9ight** [comment]
Agee to move on develop in dev

**Comment by gusprauwa** [comment]
Yeah agree on that, so it I can run both locally.

**Comment by Jesssieeee** [comment]
Good job

**Comment by TomatoesBurner** [comment]
Well done!

**Pull request merged**
