### PR TITLE
Feature/frontend backend auth

### PR DESCRIPTION
**Pull request by cloud9ight**
Complete signup and login functionalities using backend APIs. Redirect to login after signup and to user dashboard after login.

### CODE REVIEW

**Comment by thogb** [comment]
conflicts

**Comment by cloud9ight** [comment]
@TomatoesBurner can you plz check the authController.js? is it okay to make this change

**Comment by TomatoesBurner** [comment]
> @TomatoesBurner can you plz check the authController.js? is it okay to make this change

I have solved it in github editor

**Comment by cloud9ight** [comment]
[call api and test for signup and login authentication](https://trello.com/c/VX5MM6T7/29-call-api-and-test-for-signup-and-login-authentication)

**Pull request merged**
